
DROP TABLE IF EXISTS MS_USERS001_USERS;

CREATE TABLE MS_USERS001_USERS (
    USERNAME VARCHAR(100) PRIMARY KEY,
    PASSWORD VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) DEFAULT NULL
);

INSERT INTO MS_USERS001_USERS VALUES ('default', 'meow', NULL);


SELECT * FROM dbo.MS_USERS001_USERS;
